gui:
  showFileTree: false

git:
  branchLogCmd: "git log --graph --color=always --oneline --decorate --all --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
customCommands:
  - key: "<c-r>"
    command: "git push -u && gh pr create --fill --web"
    context: "global"
  - key: "n"
    description: "branch"
    command: "git checkout -b {{index .PromptResponses 0}}"
    context: "global"
    prompts:
      - type: "input"
        title: "Branch name:"
  - key: "F"
    description: "branch"
    command: "git commit --fixup=HEAD"
    context: "files"
