gui:
  sidePanelWidth: 0.25
  showCommandLog: false
  nerdFontsVersion: "3"
  commitAuthorLongLength: 2
  commitHashLength: 0
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  theme:
      selectedLineBgColor:
        - '#076678'

git:
  branchLogCmd: "git log --graph --color=always --oneline --decorate --all --pretty=format:'%C(yellow)%d%Creset %s %C(bold blue)%<(3,trunc)%an%x08%x08%Creset'"
  parseEmoji: true
notARepository: "skip"
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-r>"
    command: "git push -u && gh pr create --fill --web"
    context: "global"
  - key: "n"
    description: "branch"
    command: "git checkout -b {{index .PromptResponses 0}}"
    context: "global"
    prompts:
      - type: "input"
        title: "Branch name:"
  - key: "F"
    description: "branch"
    command: "git commit --fixup=HEAD"
    context: "files"
