gui:
  sidePanelWidth: 0.25
  nerdFontsVersion: "3"
  commitAuthorLongLength: 2
  commitHashLength: 0
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  enlargedSideViewLocation: top
  statusPanelView: allBranchesLog 
  theme:
      selectedLineBgColor:
        - '#076678'

git:
  branchLogCmd: "git log --graph --color=always --oneline --decorate --all --pretty=format:'%C(yellow)%d%Creset %s %C(bold blue)%<(5,trunc)%an%x08%x08%Creset'"
  allBranchesLogCmd: "git log --graph --color=always --oneline --decorate --all --pretty=format:'%C(yellow)%d%Creset %s %C(bold blue)%<(5,trunc)%an%x08%x08%Creset'"
  parseEmoji: true
  disableForcePushing: true
  paging:
    colorArg: always
    # pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    externalDiffCommand: difft --color=always
notARepository: "skip"
promptToReturnFromSubprocess: false
customCommands:
  - key: "n"
    description: "branch"
    command: "git checkout -b {{index .PromptResponses 0}}"
    context: "global"
    prompts:
      - type: "input"
        title: "Branch name:"
  - key: "F"
    description: "branch"
    command: "git commit --fixup=HEAD"
    context: "files"
  - key: "D"
    description: "Delete gone branches"
    command: "git dd"
    context: "localBranches"
