if vim.g.vscode == 1 then
  require "user.vscode"
else
  require "user.options"
  require "user.keymaps"
  require "user.plugins"
  require "user.notify"
  require "user.colorscheme"
  require "user.cmp"
  require "user.lsp"
  require "user.neo-tree"
  require "user.lualine"
  require "user.flutter-tools"
  require "user.telescope"
  require "user.treesitter"
  require "user.comment"
  require "user.gitsigns"
  require "user.lsp-fastaction"
  require "user.augroups"
  require "user.toggleterm"
  require "user.whichkey"
  require "user.test"
  require "user.dap"
  require "user.autopairs"
  require "user.luasnip"
  require "user.copilot"
  require "user.tabout"
  require "user.fidget"
  require "user.transparent"
end
