return {
  { "nvim-lua/popup.nvim", event = "VeryLazy" },
  { "nvim-lua/plenary.nvim", event = "VeryLazy" },
  { "kyazdani42/nvim-web-devicons", event = "VeryLazy" },
  { "moll/vim-bbye", event = "VeryLazy" },
  { "JoosepAlviste/nvim-ts-context-commentstring", event = "VeryLazy" },
  { "tpope/vim-surround", event = "VeryLazy" },
  { "tpope/vim-repeat", event = "VeryLazy" },
  { "tpope/vim-projectionist", event = "VeryLazy" },
  { "sainnhe/gruvbox-material", event = "VeryLazy" }, -- color scheme
  { "tpope/vim-unimpaired", event = "VeryLazy" },

  { "hrsh7th/cmp-buffer", event = "VeryLazy" },
  { "hrsh7th/cmp-path", event = "VeryLazy" },
  { "hrsh7th/cmp-cmdline", event = "VeryLazy" },
  { "saadparwaiz1/cmp_luasnip", event = "VeryLazy" },
  { "hrsh7th/cmp-nvim-lsp", event = "VeryLazy" },
  { "hrsh7th/cmp-nvim-lua", event = "VeryLazy" },
  { "hrsh7th/cmp-nvim-lsp-document-symbol", event = "VeryLazy" },
  { "ThePrimeagen/harpoon", event = "VeryLazy" },

  { "neovim/nvim-lspconfig", event = "VeryLazy" },
  { "williamboman/mason.nvim", event = "VeryLazy" },
  { "williamboman/mason-lspconfig.nvim", event = "VeryLazy" },
  { "jose-elias-alvarez/null-ls.nvim", event = "VeryLazy" },
  { "nvim-treesitter/nvim-treesitter-textobjects", event = "VeryLazy" },
  { "nvim-telescope/telescope-dap.nvim", event = "VeryLazy" },
  { "vim-scripts/BufOnly.vim", event = "VeryLazy" },
  { "milch/vim-fastlane", event = "VeryLazy" },
  { "delphinus/vim-firestore", event = "VeryLazy" },
  { "tpope/vim-rhubarb", event = "VeryLazy" },
  { "tpope/vim-abolish", event = "VeryLazy" },
  { "mtdl9/vim-log-highlighting", event = "VeryLazy" },
  {
    "nvim-telescope/telescope-fzf-native.nvim",
    event = "VeryLazy",
    build = "make",
  },
  { "whiteinge/diffconflicts", event = "VeryLazy" },
  { "wsdjeg/vim-fetch", event = "VeryLazy" },
  {
    "nvim-treesitter/playground",
    cmd = "TSPlaygroundToggle",
    event = "VeryLazy",
  },
  { "folke/neodev.nvim", event = "VeryLazy" },
  { "smartpde/telescope-recent-files", event = "VeryLazy" },
  { "mbbill/undotree", event = "VeryLazy" },
  { "RRethy/vim-illuminate", event = "VeryLazy" },
  { "inkarkat/vim-ReplaceWithRegister", event = "VeryLazy" },
  {
    "sidlatau/dart-lsp-refactorings.nvim",
    event = "VeryLazy",
  },
}
